### ISSUE TITLE
Can't change any setting

### ISSUE THREAD

**Issue by syfjhz22** [leitbogioro/v2ray.fun#8]
没有人遇到这样的问题吗?

> 1.更改UUID
> 2.更改主端口
> 3.更改加密方式
> 4.更改传输方式
> 5.更改TLS设置
> 6.更改自动维护功能
> 7.更改额外Id
> 8.更改动态端口
> 9.更改路径
> 请输入数字选择功能：
> 
> 请选择： 1
> 
>   File "/usr/local/v2ray.fun/changeuuid.py", line 12
>     print "新的UUID为：{}".format(newuuid)
>                      ^
> SyntaxError: invalid syntax
> Traceback (most recent call last):
>   File "/usr/local/v2ray.fun/genclient.py", line 5, in <module>
>     import readjson
>   File "/usr/local/v2ray.fun/readjson.py", line 6, in <module>
>     jsonFile = file("/etc/v2ray/config.json")
> NameError: name 'file' is not defined
> 
> UUID修改成功！

**Comment by leitbogioro** [comment]
看报错是因为/etc/v2ray/config.json文件丢失导致的，你在使用的是什么系统？是否是纯净环境安装的？

**Comment by hkvsak** [comment]
1.服务管理
2.更改配置
3.查看服务端信息
4.下载客户端配置文件
5.更新 V2ray 和 V2ray.Fun
请输入数字选择功能(按回车键退出)：

请选择： 3

Traceback (most recent call last):
  File "/usr/local/v2ray.fun/serverinfo.py", line 4, in <module>
    import readjson
  File "/usr/local/v2ray.fun/readjson.py", line 12, in <module>
    ConfInboundDetour = config[u"inboundDetour"]
KeyError: u'inboundDetour'

欢迎使用 V2ray.Fun 管理程序

1.服务管理
2.更改配置
3.查看服务端信息
4.下载客户端配置文件
5.更新 V2ray 和 V2ray.Fun
请输入数字选择功能(按回车键退出)：

请选择： 


这是什么问题?

**Comment by hkvsak** [comment]
输入数字无效
